name: code_coverage

on:
  workflow_run:
    workflows: [ android_ci ]
    types: [ completed ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  API_KEY: ${{ secrets.API_KEY }}
  GPR_USERNAME: ${{ secrets.GPR_USERNAME }}
  GPR_KEY: ${{ secrets.GPR_KEY }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  code_coverage:
    runs-on: macos-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-based-on-the-conclusion-of-another-workflow
    strategy:
      matrix:
        api-level: [ 29 ]
    steps:
      - name: checkout project sources
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: set up jdk 20
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '20'

      - name: create local.properties from secret variables
        run: orb/scripts/generate_user_properties.sh

      - name: setup gradle
        uses: gradle/gradle-build-action@v3

      - name: avd cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create avd and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          script: echo "generated avd snapshot for caching."

      - name: run ui tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -wipe-data # Emulator options reference: https://developer.android.com/studio/run/emulator-commandline
          disable-animations: true
          script: ./gradlew verifyCodeCoverage

      - name: archive ui test reports on failure
        uses: actions/upload-artifact@v4
        with:
          name: code_coverage
          path: "**/build/reports/jacoco"